name: flutter_medical_data_app
description: "Medikal Uygulama"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  responsive_sizer: ^3.3.1
  intl: ^0.20.2
  smart_popup: ^3.0.4
  logger: ^2.6.1
  flutter_launcher_icons: ^0.14.4
  lottie: ^3.3.2
  #Firebase
  firebase_messaging: ^16.0.2
  google_sign_in: ^7.2.0
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  dotted_border: ^3.1.0
  share_plus: ^12.0.0
  app_links: ^6.3.4
  csv: ^6.0.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/logo/
    - assets/lottie/

  fonts: 
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200


